/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.nu.ui;

import edu.nu.content.Driver;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author sujayghodke
 */
public class CreateDrivJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateDrivJPanel
     */
    Driver driv;
    public CreateDrivJPanel(Driver driv) {
        initComponents();
        this.driv = driv;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLicenseNo = new javax.swing.JLabel();
        txtBlood = new javax.swing.JTextField();
        lblIssueDate = new javax.swing.JLabel();
        lblExpDate = new javax.swing.JLabel();
        lblBlood = new javax.swing.JLabel();
        txtLicenseNo = new javax.swing.JTextField();
        txtIssueDate = new javax.swing.JTextField();
        lblTitleDriv = new javax.swing.JLabel();
        txtExpDate = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lblPicture = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 153));

        lblLicenseNo.setText("License Number:");

        txtBlood.setBackground(new java.awt.Color(204, 204, 204));

        lblIssueDate.setText("Issue Date:");

        lblExpDate.setText("Expiry Date:");

        lblBlood.setText("Blood Group:");

        txtLicenseNo.setBackground(new java.awt.Color(204, 204, 204));

        txtIssueDate.setBackground(new java.awt.Color(204, 204, 204));

        lblTitleDriv.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblTitleDriv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleDriv.setText("Enter your driver's license details below:");

        txtExpDate.setBackground(new java.awt.Color(204, 204, 204));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblPicture.setText("Picture:");

        jButton1.setText("Upload");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitleDriv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIssueDate)
                            .addComponent(lblLicenseNo)
                            .addComponent(lblExpDate)
                            .addComponent(lblBlood)
                            .addComponent(lblPicture))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBlood, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtExpDate, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIssueDate, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLicenseNo, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(115, 115, 115)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(lblTitleDriv)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLicenseNo)
                    .addComponent(txtLicenseNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIssueDate)
                    .addComponent(txtIssueDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExpDate)
                    .addComponent(txtExpDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBlood)
                    .addComponent(txtBlood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPicture)
                    .addComponent(jButton1))
                .addGap(34, 34, 34)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        driv.setLicense_no(txtLicenseNo.getText());
        
        driv.setIssue_date(txtIssueDate.getText());
        driv.setExp_date(txtExpDate.getText());
        driv.setBlood_type(txtBlood.getText());

        JOptionPane.showMessageDialog(this, "Your drivers license details are saved. \n "
            + "Please click on create button next to Medical to enter further information.");
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser uploadImage = new JFileChooser();
        
        
        
        int temp = uploadImage.showOpenDialog(null);
        if (temp == JFileChooser.APPROVE_OPTION){
            File selectedImageFile = uploadImage.getSelectedFile();
            String selectedImagePath = selectedImageFile.getAbsolutePath();
            JOptionPane.showMessageDialog(this, selectedImagePath+" is now selected.");
            
            driv.setPicture(selectedImagePath);
           
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblBlood;
    private javax.swing.JLabel lblExpDate;
    private javax.swing.JLabel lblIssueDate;
    private javax.swing.JLabel lblLicenseNo;
    private javax.swing.JLabel lblPicture;
    private javax.swing.JLabel lblTitleDriv;
    private javax.swing.JTextField txtBlood;
    private javax.swing.JTextField txtExpDate;
    private javax.swing.JTextField txtIssueDate;
    private javax.swing.JTextField txtLicenseNo;
    // End of variables declaration//GEN-END:variables
}
