/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.nu.ui;

import edu.nu.content.Account;
import javax.swing.JOptionPane;

/**
 *
 * @author sujayghodke
 */
public class CreateAccJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateAccJPanel
     */
    
    Account acc;
    public CreateAccJPanel(Account acc) {
        initComponents();
        this.acc = acc;
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAccNo = new javax.swing.JLabel();
        lblAccBal = new javax.swing.JLabel();
        txtBank = new javax.swing.JTextField();
        lblRouting = new javax.swing.JLabel();
        txtRouting = new javax.swing.JTextField();
        lblTitleAcc = new javax.swing.JLabel();
        txtAccNo = new javax.swing.JTextField();
        lblBank = new javax.swing.JLabel();
        txtAccBal = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lblAccType = new javax.swing.JLabel();
        radioSaving = new javax.swing.JRadioButton();
        radioChecking = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(153, 153, 153));

        lblAccNo.setText("Account Number:");

        lblAccBal.setText("Account Balance:");

        txtBank.setBackground(new java.awt.Color(204, 204, 204));

        lblRouting.setText("Routing Number:");

        txtRouting.setBackground(new java.awt.Color(204, 204, 204));

        lblTitleAcc.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblTitleAcc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleAcc.setText("Enter your bank account details below:");

        txtAccNo.setBackground(new java.awt.Color(204, 204, 204));

        lblBank.setText("Bank Name:");

        txtAccBal.setBackground(new java.awt.Color(204, 204, 204));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblAccType.setText("Account Type:");

        radioSaving.setText("Saving");
        radioSaving.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSavingActionPerformed(evt);
            }
        });

        radioChecking.setText("Checking");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitleAcc, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRouting)
                                    .addComponent(lblBank)
                                    .addComponent(lblAccNo)
                                    .addComponent(lblAccBal)
                                    .addComponent(lblAccType))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtAccBal, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtRouting, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtBank, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(radioSaving)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radioChecking))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(115, 115, 115)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(lblTitleAcc)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBank)
                    .addComponent(txtBank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRouting)
                    .addComponent(txtRouting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccNo)
                    .addComponent(txtAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccBal)
                    .addComponent(txtAccBal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioSaving)
                    .addComponent(radioChecking)
                    .addComponent(lblAccType))
                .addGap(40, 40, 40)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(131, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        acc.setBank(txtBank.getText());
        acc.setRouting(txtRouting.getText());
        acc.setAcc_no(txtAccNo.getText());
        acc.setAcc_bal(txtAccBal.getText());
        
        if(radioSaving.isSelected()){
            acc.setAcc_type(radioSaving.getText());
        }
        else{
            acc.setAcc_type(radioChecking.getText());
        }

        JOptionPane.showMessageDialog(this, "Your bank details are saved. \n "
                + "Please click on create button next to Driver's License to enter further information.");
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void radioSavingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSavingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioSavingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblAccBal;
    private javax.swing.JLabel lblAccNo;
    private javax.swing.JLabel lblAccType;
    private javax.swing.JLabel lblBank;
    private javax.swing.JLabel lblRouting;
    private javax.swing.JLabel lblTitleAcc;
    private javax.swing.JRadioButton radioChecking;
    private javax.swing.JRadioButton radioSaving;
    private javax.swing.JTextField txtAccBal;
    private javax.swing.JTextField txtAccNo;
    private javax.swing.JTextField txtBank;
    private javax.swing.JTextField txtRouting;
    // End of variables declaration//GEN-END:variables
}
