/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.nu.ui;

import edu.nu.content.Account;
import edu.nu.content.Address;
import edu.nu.content.Demographic;
import edu.nu.content.Driver;
import edu.nu.content.Medical;
import javax.swing.ImageIcon;

/**
 *
 * @author sujayghodke
 */
public class ViewReportJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewReportJPanel
     */
    Demographic demo;
    Address addr;
    Account acc;
    Driver driv;
    Medical med;
    
    public ViewReportJPanel(Demographic demo, Address addr, Account acc, Driver driv, Medical med) {
        initComponents();
        this.demo = demo;
        this.addr = addr;
        this.acc = acc;
        this.driv = driv;
        this.med = med;
        
        displayDemo();
        displayAddress();
        displayAccount();
        displayDriv();
        displayMed();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitleMed = new javax.swing.JLabel();
        txtWeight = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        txtSsn = new javax.swing.JTextField();
        lblHeight = new javax.swing.JLabel();
        lblWeight = new javax.swing.JLabel();
        lblSsn = new javax.swing.JLabel();
        txtFname = new javax.swing.JTextField();
        txtLname = new javax.swing.JTextField();
        lblTitleDemo = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        lblFname = new javax.swing.JLabel();
        txtDob = new javax.swing.JTextField();
        lblLname = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        lblPhone = new javax.swing.JLabel();
        txtHeight = new javax.swing.JTextField();
        lblDob = new javax.swing.JLabel();
        lblTitleDemo1 = new javax.swing.JLabel();
        lblFname1 = new javax.swing.JLabel();
        txtLicenseNo = new javax.swing.JTextField();
        lblLname1 = new javax.swing.JLabel();
        txtIssueDate = new javax.swing.JTextField();
        lblPhone1 = new javax.swing.JLabel();
        txtExpDate = new javax.swing.JTextField();
        lblDob1 = new javax.swing.JLabel();
        txtBlood = new javax.swing.JTextField();
        lblTitleDemo2 = new javax.swing.JLabel();
        lblFname2 = new javax.swing.JLabel();
        txtRecordNo = new javax.swing.JTextField();
        lblLname2 = new javax.swing.JLabel();
        txtAll1 = new javax.swing.JTextField();
        lblPhone2 = new javax.swing.JLabel();
        txtAll2 = new javax.swing.JTextField();
        lblDob2 = new javax.swing.JLabel();
        txtAll3 = new javax.swing.JTextField();
        lblTitleDemo3 = new javax.swing.JLabel();
        lblFname3 = new javax.swing.JLabel();
        lblLname3 = new javax.swing.JLabel();
        lblPhone3 = new javax.swing.JLabel();
        lblDob3 = new javax.swing.JLabel();
        txtStreetAddr = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtState = new javax.swing.JTextField();
        txtZip = new javax.swing.JTextField();
        lblTitleDemo4 = new javax.swing.JLabel();
        txtAccNo = new javax.swing.JTextField();
        lblFname4 = new javax.swing.JLabel();
        txtAccBal = new javax.swing.JTextField();
        lblLname4 = new javax.swing.JLabel();
        txtAccType = new javax.swing.JTextField();
        lblPhone4 = new javax.swing.JLabel();
        lblDob4 = new javax.swing.JLabel();
        lblAge1 = new javax.swing.JLabel();
        txtBank = new javax.swing.JTextField();
        txtRouting = new javax.swing.JTextField();
        lblPictureDisplay = new javax.swing.JLabel();
        lblDob5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 153));

        lblTitleMed.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblTitleMed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleMed.setText("Generated Report");

        txtWeight.setEditable(false);
        txtWeight.setBackground(new java.awt.Color(204, 204, 204));
        txtWeight.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N

        lblAge.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblAge.setText("Age:");

        txtSsn.setEditable(false);
        txtSsn.setBackground(new java.awt.Color(204, 204, 204));
        txtSsn.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N

        lblHeight.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblHeight.setText("Height:");

        lblWeight.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblWeight.setText("Weight:");

        lblSsn.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblSsn.setText("SSN:");

        txtFname.setEditable(false);
        txtFname.setBackground(new java.awt.Color(204, 204, 204));
        txtFname.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N

        txtLname.setEditable(false);
        txtLname.setBackground(new java.awt.Color(204, 204, 204));
        txtLname.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N

        lblTitleDemo.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        lblTitleDemo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleDemo.setText("Demographic Information");

        txtPhone.setEditable(false);
        txtPhone.setBackground(new java.awt.Color(204, 204, 204));
        txtPhone.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N

        lblFname.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblFname.setText("First Name:");

        txtDob.setEditable(false);
        txtDob.setBackground(new java.awt.Color(204, 204, 204));
        txtDob.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N

        lblLname.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblLname.setText("Last Name:");

        txtAge.setEditable(false);
        txtAge.setBackground(new java.awt.Color(204, 204, 204));
        txtAge.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N

        lblPhone.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblPhone.setText("Phone:");

        txtHeight.setEditable(false);
        txtHeight.setBackground(new java.awt.Color(204, 204, 204));
        txtHeight.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N

        lblDob.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblDob.setText("Date of Birth:");

        lblTitleDemo1.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        lblTitleDemo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleDemo1.setText("Driver's License Details");

        lblFname1.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblFname1.setText("License No:");

        txtLicenseNo.setEditable(false);
        txtLicenseNo.setBackground(new java.awt.Color(204, 204, 204));
        txtLicenseNo.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N

        lblLname1.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblLname1.setText("Issue Date:");

        txtIssueDate.setEditable(false);
        txtIssueDate.setBackground(new java.awt.Color(204, 204, 204));
        txtIssueDate.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N

        lblPhone1.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblPhone1.setText("Expiry Date:");

        txtExpDate.setEditable(false);
        txtExpDate.setBackground(new java.awt.Color(204, 204, 204));
        txtExpDate.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N

        lblDob1.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblDob1.setText("Blood Group:");

        txtBlood.setEditable(false);
        txtBlood.setBackground(new java.awt.Color(204, 204, 204));
        txtBlood.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N

        lblTitleDemo2.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        lblTitleDemo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleDemo2.setText("Medical Information");

        lblFname2.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblFname2.setText("Record No:");

        txtRecordNo.setEditable(false);
        txtRecordNo.setBackground(new java.awt.Color(204, 204, 204));
        txtRecordNo.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N

        lblLname2.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblLname2.setText("Allergy 1:");

        txtAll1.setEditable(false);
        txtAll1.setBackground(new java.awt.Color(204, 204, 204));
        txtAll1.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N

        lblPhone2.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblPhone2.setText("Allergy 2:");

        txtAll2.setEditable(false);
        txtAll2.setBackground(new java.awt.Color(204, 204, 204));
        txtAll2.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N

        lblDob2.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblDob2.setText("Allergy 3:");

        txtAll3.setEditable(false);
        txtAll3.setBackground(new java.awt.Color(204, 204, 204));
        txtAll3.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N

        lblTitleDemo3.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        lblTitleDemo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleDemo3.setText("Address");

        lblFname3.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblFname3.setText("Street:");

        lblLname3.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblLname3.setText("City:");

        lblPhone3.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblPhone3.setText("State:");

        lblDob3.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblDob3.setText("Zip Code:");

        txtStreetAddr.setEditable(false);
        txtStreetAddr.setBackground(new java.awt.Color(204, 204, 204));
        txtStreetAddr.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N

        txtCity.setEditable(false);
        txtCity.setBackground(new java.awt.Color(204, 204, 204));
        txtCity.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N

        txtState.setEditable(false);
        txtState.setBackground(new java.awt.Color(204, 204, 204));
        txtState.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N

        txtZip.setEditable(false);
        txtZip.setBackground(new java.awt.Color(204, 204, 204));
        txtZip.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N

        lblTitleDemo4.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        lblTitleDemo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleDemo4.setText("Bank Account");

        txtAccNo.setEditable(false);
        txtAccNo.setBackground(new java.awt.Color(204, 204, 204));
        txtAccNo.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N

        lblFname4.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblFname4.setText("Bank Name:");

        txtAccBal.setEditable(false);
        txtAccBal.setBackground(new java.awt.Color(204, 204, 204));
        txtAccBal.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N

        lblLname4.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblLname4.setText("Routing No:");

        txtAccType.setEditable(false);
        txtAccType.setBackground(new java.awt.Color(204, 204, 204));
        txtAccType.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N

        lblPhone4.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblPhone4.setText("Account No:");

        lblDob4.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblDob4.setText("Balance:");

        lblAge1.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblAge1.setText("Type:");

        txtBank.setEditable(false);
        txtBank.setBackground(new java.awt.Color(204, 204, 204));
        txtBank.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N

        txtRouting.setEditable(false);
        txtRouting.setBackground(new java.awt.Color(204, 204, 204));
        txtRouting.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N

        lblDob5.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblDob5.setText("Uploaded Picture:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblPhone)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblLname)
                            .addGap(18, 18, 18)
                            .addComponent(txtLname, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDob)
                            .addComponent(lblAge)
                            .addComponent(lblHeight)
                            .addComponent(lblWeight)
                            .addComponent(lblSsn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSsn)
                            .addComponent(txtWeight, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(txtDob)
                            .addComponent(txtAge)
                            .addComponent(txtHeight)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblTitleDemo, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblFname)
                            .addGap(18, 18, 18)
                            .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblLname3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPhone3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDob3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtZip, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFname3)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCity, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(txtStreetAddr)))
                    .addComponent(lblTitleDemo2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblLname2)
                            .addGap(24, 24, 24)
                            .addComponent(txtAll1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblFname2)
                            .addGap(18, 18, 18)
                            .addComponent(txtRecordNo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblPhone2)
                            .addGap(24, 24, 24)
                            .addComponent(txtAll2, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblDob2)
                            .addGap(24, 24, 24)
                            .addComponent(txtAll3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblTitleDemo3, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblTitleDemo1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(lblAge1)
                                            .addGap(44, 44, 44)
                                            .addComponent(txtAccType))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblLname4)
                                                .addComponent(lblFname4))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtBank, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                                .addComponent(txtRouting)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(lblDob4)
                                            .addGap(29, 29, 29)
                                            .addComponent(txtAccBal))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(lblPhone4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblLname1)
                                            .addComponent(lblPhone1)
                                            .addComponent(lblFname1))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtLicenseNo, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtIssueDate)
                                            .addComponent(txtExpDate)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblDob1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtBlood)))
                                .addGap(120, 126, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(lblTitleDemo4, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(lblDob5)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPictureDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(175, 175, 175))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitleMed, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtAge, txtDob, txtFname, txtHeight, txtLname, txtPhone, txtSsn, txtWeight});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtAll1, txtAll2, txtAll3, txtRecordNo});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtCity, txtState, txtStreetAddr, txtZip});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtBlood, txtExpDate, txtIssueDate, txtLicenseNo});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitleMed)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitleDemo)
                    .addComponent(lblTitleDemo4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFname)
                            .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLname)
                            .addComponent(txtLname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPhone)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDob)
                            .addComponent(txtDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBank, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(lblFname4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLname4)
                            .addComponent(txtRouting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPhone4)
                            .addComponent(txtAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDob4)
                            .addComponent(txtAccBal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAge)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAge1)
                            .addComponent(txtAccType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHeight)
                            .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblWeight)
                            .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSsn)
                            .addComponent(txtSsn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTitleDemo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFname2)
                            .addComponent(txtRecordNo, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLname2)
                            .addComponent(txtAll1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPhone2)
                            .addComponent(txtAll2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDob2)
                            .addComponent(txtAll3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTitleDemo3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFname3)
                            .addComponent(txtStreetAddr, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLname3)
                            .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPhone3)
                            .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTitleDemo1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFname1)
                            .addComponent(txtLicenseNo, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLname1)
                            .addComponent(txtIssueDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPhone1)
                            .addComponent(txtExpDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDob1)
                            .addComponent(txtBlood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDob5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPictureDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDob3)
                    .addComponent(txtZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtAge, txtDob, txtFname, txtHeight, txtLname, txtPhone, txtSsn, txtWeight});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtBlood, txtExpDate, txtIssueDate, txtLicenseNo});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtAll1, txtAll2, txtAll3, txtRecordNo});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtCity, txtState, txtStreetAddr, txtZip});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtAccBal, txtAccNo, txtAccType, txtBank, txtRouting});

    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblAge1;
    private javax.swing.JLabel lblDob;
    private javax.swing.JLabel lblDob1;
    private javax.swing.JLabel lblDob2;
    private javax.swing.JLabel lblDob3;
    private javax.swing.JLabel lblDob4;
    private javax.swing.JLabel lblDob5;
    private javax.swing.JLabel lblFname;
    private javax.swing.JLabel lblFname1;
    private javax.swing.JLabel lblFname2;
    private javax.swing.JLabel lblFname3;
    private javax.swing.JLabel lblFname4;
    private javax.swing.JLabel lblHeight;
    private javax.swing.JLabel lblLname;
    private javax.swing.JLabel lblLname1;
    private javax.swing.JLabel lblLname2;
    private javax.swing.JLabel lblLname3;
    private javax.swing.JLabel lblLname4;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPhone1;
    private javax.swing.JLabel lblPhone2;
    private javax.swing.JLabel lblPhone3;
    private javax.swing.JLabel lblPhone4;
    private javax.swing.JLabel lblPictureDisplay;
    private javax.swing.JLabel lblSsn;
    private javax.swing.JLabel lblTitleDemo;
    private javax.swing.JLabel lblTitleDemo1;
    private javax.swing.JLabel lblTitleDemo2;
    private javax.swing.JLabel lblTitleDemo3;
    private javax.swing.JLabel lblTitleDemo4;
    private javax.swing.JLabel lblTitleMed;
    private javax.swing.JLabel lblWeight;
    private javax.swing.JTextField txtAccBal;
    private javax.swing.JTextField txtAccNo;
    private javax.swing.JTextField txtAccType;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtAll1;
    private javax.swing.JTextField txtAll2;
    private javax.swing.JTextField txtAll3;
    private javax.swing.JTextField txtBank;
    private javax.swing.JTextField txtBlood;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtDob;
    private javax.swing.JTextField txtExpDate;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtIssueDate;
    private javax.swing.JTextField txtLicenseNo;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtRecordNo;
    private javax.swing.JTextField txtRouting;
    private javax.swing.JTextField txtSsn;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtStreetAddr;
    private javax.swing.JTextField txtWeight;
    private javax.swing.JTextField txtZip;
    // End of variables declaration//GEN-END:variables

        
    private void displayDemo() {
        txtFname.setText(demo.getFirst_name());
        txtLname.setText(demo.getLast_name());
        txtPhone.setText(demo.getPhone());
        txtDob.setText(demo.getDob());
        txtAge.setText(demo.getAge());
        txtHeight.setText(demo.getHeight());
        txtWeight.setText(demo.getWeight());
        txtSsn.setText(demo.getSsn());
        
    }
    
    private void displayAddress() {
        txtStreetAddr.setText(addr.getStreet());
        txtCity.setText(addr.getCity());
        txtState.setText(addr.getState());
        txtZip.setText(addr.getZip());
    }
    
    private void displayAccount() {
        txtBank.setText(acc.getBank());
        txtRouting.setText(acc.getRouting());
        txtAccNo.setText(acc.getAcc_no());
        txtAccBal.setText(acc.getAcc_bal());
        txtAccType.setText(acc.getAcc_type());
    }
    
    private void displayDriv() {
        txtLicenseNo.setText(driv.getLicense_no());
        txtIssueDate.setText(driv.getIssue_date());
        txtExpDate.setText(driv.getExp_date());
        txtBlood.setText(driv.getBlood_type());
        
        ImageIcon iconObj = new ImageIcon(driv.getPicture());
        lblPictureDisplay.setIcon(iconObj);
        
    }
    
    private void displayMed() {
        txtRecordNo.setText(med.getRec_no());
        txtAll1.setText(med.getAllergy1());
        txtAll2.setText(med.getAllergy2());
        txtAll3.setText(med.getAllergy3());
    }
        
        

}
