/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.nu.ui;

import edu.nu.content.Account;

/**
 *
 * @author sujayghodke
 */
public class ViewAccJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewAccJPanel
     */
    
    Account acc;
    public ViewAccJPanel(Account acc) {
        initComponents();
        this.acc = acc;
        
        displayAccount();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRouting = new javax.swing.JLabel();
        lblAccType = new javax.swing.JLabel();
        lblAccNo = new javax.swing.JLabel();
        lblAccBal = new javax.swing.JLabel();
        txtBank = new javax.swing.JTextField();
        txtRouting = new javax.swing.JTextField();
        lblTitleAcc = new javax.swing.JLabel();
        txtAccNo = new javax.swing.JTextField();
        lblBank = new javax.swing.JLabel();
        txtAccBal = new javax.swing.JTextField();
        txtAccType = new javax.swing.JTextField();

        setBackground(new java.awt.Color(153, 153, 153));

        lblRouting.setText("Routing Number:");

        lblAccType.setText("Account Type:");

        lblAccNo.setText("Account Number:");

        lblAccBal.setText("Account Balance:");

        txtBank.setBackground(new java.awt.Color(204, 204, 204));

        txtRouting.setBackground(new java.awt.Color(204, 204, 204));

        lblTitleAcc.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblTitleAcc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleAcc.setText("Bank Account Details");

        txtAccNo.setBackground(new java.awt.Color(204, 204, 204));

        lblBank.setText("Bank Name:");

        txtAccBal.setBackground(new java.awt.Color(204, 204, 204));

        txtAccType.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitleAcc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRouting)
                            .addComponent(lblBank)
                            .addComponent(lblAccNo)
                            .addComponent(lblAccBal)
                            .addComponent(lblAccType))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAccBal, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRouting, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBank, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAccType, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(lblTitleAcc)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBank)
                    .addComponent(txtBank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRouting)
                    .addComponent(txtRouting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccNo)
                    .addComponent(txtAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccBal)
                    .addComponent(txtAccBal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccType)
                    .addComponent(txtAccType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(259, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAccBal;
    private javax.swing.JLabel lblAccNo;
    private javax.swing.JLabel lblAccType;
    private javax.swing.JLabel lblBank;
    private javax.swing.JLabel lblRouting;
    private javax.swing.JLabel lblTitleAcc;
    private javax.swing.JTextField txtAccBal;
    private javax.swing.JTextField txtAccNo;
    private javax.swing.JTextField txtAccType;
    private javax.swing.JTextField txtBank;
    private javax.swing.JTextField txtRouting;
    // End of variables declaration//GEN-END:variables

    private void displayAccount() {
        txtBank.setText(acc.getBank());
        txtRouting.setText(acc.getRouting());
        txtAccNo.setText(acc.getAcc_no());
        txtAccBal.setText(acc.getAcc_bal());
        txtAccType.setText(acc.getAcc_type());
    }
}
