/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.nu.ui;

import edu.nu.content.Medical;

/**
 *
 * @author sujayghodke
 */
public class ViewMedJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewMedJPanel
     */
    Medical med;
    public ViewMedJPanel(Medical med) {
        initComponents();
        this.med = med;
        
        displayMed();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRecordNo = new javax.swing.JLabel();
        txtAll3 = new javax.swing.JTextField();
        lblAll1 = new javax.swing.JLabel();
        lblAll2 = new javax.swing.JLabel();
        lblAll3 = new javax.swing.JLabel();
        txtRecordNo = new javax.swing.JTextField();
        txtAll1 = new javax.swing.JTextField();
        lblTitleMed = new javax.swing.JLabel();
        txtAll2 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(153, 153, 153));

        lblRecordNo.setText("Record Number:");

        txtAll3.setBackground(new java.awt.Color(204, 204, 204));

        lblAll1.setText("Allergy 1:");

        lblAll2.setText("Allergy 2:");

        lblAll3.setText("Allergy 3:");

        txtRecordNo.setBackground(new java.awt.Color(204, 204, 204));

        txtAll1.setBackground(new java.awt.Color(204, 204, 204));

        lblTitleMed.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblTitleMed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleMed.setText("Medical Information");

        txtAll2.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitleMed, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAll1)
                            .addComponent(lblRecordNo)
                            .addComponent(lblAll2)
                            .addComponent(lblAll3))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAll3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAll2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAll1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRecordNo, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(115, 115, 115)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(lblTitleMed)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRecordNo)
                    .addComponent(txtRecordNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAll1)
                    .addComponent(txtAll1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAll2)
                    .addComponent(txtAll2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAll3)
                    .addComponent(txtAll3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(316, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAll1;
    private javax.swing.JLabel lblAll2;
    private javax.swing.JLabel lblAll3;
    private javax.swing.JLabel lblRecordNo;
    private javax.swing.JLabel lblTitleMed;
    private javax.swing.JTextField txtAll1;
    private javax.swing.JTextField txtAll2;
    private javax.swing.JTextField txtAll3;
    private javax.swing.JTextField txtRecordNo;
    // End of variables declaration//GEN-END:variables

    private void displayMed() {
        txtRecordNo.setText(med.getRec_no());
        txtAll1.setText(med.getAllergy1());
        txtAll2.setText(med.getAllergy2());
        txtAll3.setText(med.getAllergy3());
    }
}
