/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.nu.ui;

import edu.nu.content.Driver;
import javax.swing.ImageIcon;

/**
 *
 * @author sujayghodke
 */
public class ViewDrivJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewDrivJPanel
     */
    Driver driv;
    public ViewDrivJPanel(Driver driv) {
        initComponents();
        this.driv = driv;
        
        displayDriv();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBlood = new javax.swing.JTextField();
        lblIssueDate = new javax.swing.JLabel();
        lblExpDate = new javax.swing.JLabel();
        lblBlood = new javax.swing.JLabel();
        txtLicenseNo = new javax.swing.JTextField();
        txtIssueDate = new javax.swing.JTextField();
        lblTitleDriv = new javax.swing.JLabel();
        txtExpDate = new javax.swing.JTextField();
        lblPicture = new javax.swing.JLabel();
        lblLicenseNo = new javax.swing.JLabel();
        lblPictureDisplay = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 153));

        txtBlood.setEditable(false);
        txtBlood.setBackground(new java.awt.Color(204, 204, 204));

        lblIssueDate.setText("Issue Date:");

        lblExpDate.setText("Expiry Date:");

        lblBlood.setText("Blood Group:");

        txtLicenseNo.setEditable(false);
        txtLicenseNo.setBackground(new java.awt.Color(204, 204, 204));

        txtIssueDate.setEditable(false);
        txtIssueDate.setBackground(new java.awt.Color(204, 204, 204));

        lblTitleDriv.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblTitleDriv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleDriv.setText("Driver's License Details");

        txtExpDate.setEditable(false);
        txtExpDate.setBackground(new java.awt.Color(204, 204, 204));

        lblPicture.setText("Picture:");

        lblLicenseNo.setText("License Number:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitleDriv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIssueDate)
                            .addComponent(lblLicenseNo)
                            .addComponent(lblExpDate)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblPicture)
                                .addComponent(lblBlood)))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBlood, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(txtExpDate, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(txtIssueDate, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(txtLicenseNo, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(lblPictureDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(115, 115, 115)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(lblTitleDriv)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLicenseNo)
                    .addComponent(txtLicenseNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIssueDate)
                    .addComponent(txtIssueDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExpDate)
                    .addComponent(txtExpDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBlood)
                    .addComponent(txtBlood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lblPictureDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(lblPicture)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBlood;
    private javax.swing.JLabel lblExpDate;
    private javax.swing.JLabel lblIssueDate;
    private javax.swing.JLabel lblLicenseNo;
    private javax.swing.JLabel lblPicture;
    private javax.swing.JLabel lblPictureDisplay;
    private javax.swing.JLabel lblTitleDriv;
    private javax.swing.JTextField txtBlood;
    private javax.swing.JTextField txtExpDate;
    private javax.swing.JTextField txtIssueDate;
    private javax.swing.JTextField txtLicenseNo;
    // End of variables declaration//GEN-END:variables

    private void displayDriv() {
        txtLicenseNo.setText(driv.getLicense_no());
        txtIssueDate.setText(driv.getIssue_date());
        txtExpDate.setText(driv.getExp_date());
        txtBlood.setText(driv.getBlood_type());
        
        ImageIcon iconObj = new ImageIcon(driv.getPicture());
        lblPictureDisplay.setIcon(iconObj);
    }
}
